[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cp_amm = "ASmKWt93JEMHxbdE6j7znD9y2FcdPboCzC3xtSTJvN7S"
fee_router = "5B57SJ3g2YoNXUpsZqqjEQkRSxyKtVTQRXdgAirz6bio"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "keys/local/admin-bossj3JvwiNK7pvjr149DqdtJxf2gdygbcmEPTkb2F1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
