[features]
seeds = false
skip-lint = false
[programs.localnet]
cp_amm = "3VcoGUqpWGa9a2GCCDM3osCH6bYoaNMoV9J1cpmQzSwD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keys/local/admin-bossj3JvwiNK7pvjr149DqdtJxf2gdygbcmEPTkb2F1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
