name: CP-AMM

on:
  pull_request:
    branches:
      - main
      - staging

env:
  SOLANA_CLI_VERSION: 1.16.1
  NODE_VERSION: 18.20.6
  ANCHOR_CLI_VERSION: 0.29.0

jobs:
  program_changed_files:
    runs-on: ubuntu-latest
    outputs:
      program: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            programs/cp-amm

  anchor_build:
    runs-on: ubuntu-latest
    needs: program_changed_files
    if: needs.program_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-solana
      - uses: ./.github/actions/setup-dep
      - uses: ./.github/actions/setup-anchor
       # Cache rust, cargo
      - uses: Swatinem/rust-cache@v1
      - run: anchor build
        shell: bash

  cli_build:
    runs-on: ubuntu-latest
    needs: program_changed_files
    if: needs.program_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v4
      # Install rust + toolchain
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.76.0
          components: clippy
      - run: rustup target add x86_64-unknown-linux-gnu
      # Cache rust, cargo
      - uses: Swatinem/rust-cache@v1
      - run: cargo build -p cli --target=x86_64-unknown-linux-gnu
        shell: bash

  cargo_test:
    runs-on: ubuntu-latest
    needs: program_changed_files
    if: needs.program_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.76.0
          components: clippy
      - run: rustup target add x86_64-unknown-linux-gnu
      # Cache rust, cargo
      - uses: Swatinem/rust-cache@v1
      - run: cargo test --package cp-amm --target=x86_64-unknown-linux-gnu
        shell: bash

  program_test:
    runs-on: ubuntu-latest
    needs: program_changed_files
    if: needs.program_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-solana
      - uses: ./.github/actions/setup-dep
      - uses: ./.github/actions/setup-anchor
      # Install pnpm
      - uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 9.5.0 # Optional: specify a pnpm version
      # Install rust + toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      # Cache rust, cargo
      - uses: Swatinem/rust-cache@v1
      # Cache node_modules
      - uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      # Testing
      - run: pnpm install
        shell: bash
      - run: pnpm test
        shell: bash
